language: go 
go:
  - "1.14"
env:
  - GO111MODULE=on
services:
  - mongodb
before_script:
  - sleep 15 # https://docs.travis-ci.com/user/database-setup/#mongodb-does-not-immediately-accept-connections
  - wget http://downloads.mongodb.org/linux/mongodb-linux-x86_64-v4.0-latest.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - sudo service mongod stop
  - sudo cp /tmp/mongodb-linux-x86_64-v4.0/bin/mongod  /usr/bin/mongod
  - sudo service mongod start
  - sleep 30

script:
  - mongod --version
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)