language: go 
go:
  - "1.14"
env:
  - GO111MODULE=on
services:
  - mongodb
before_script:
  - sleep 15 # https://docs.travis-ci.com/user/database-setup/#mongodb-does-not-immediately-accept-connections
